// Organizations
const Sororities = [
    "Alpha Delta Pi",
    "Alpha Gamma Delta",
    "Alpha Omega Epsilon",
    "Alpha Phi",
    "Alpha Xi Delta",
    "Kappa Alpha Theta",
    "Phi Mu",
    "Zeta Tau Alpha"
];
const Fraternities = [
    "Alpha Epsilon Pi",
    "Alpha Sigma Phi",
    "Alpha Tau Omega",
    "Beta Theta Pi",
    "Chi Phi",
    "Chi Psi",
    "Delta Chi",
    "Delta Sigma Phi",
    "Delta Tau Delta",
    "Delta Upsilon",
    "Kappa Alpha Order",
    "Kappa Sigma",
    "Lambda Chi Alpha",
    "Phi Delta Theta",
    "Phi Gamma Delta",
    "Phi Kappa Psi",
    "Phi Kappa Sigma",
    "Phi Kappa Theta",
    "Phi Sigma Kappa",
    "Pi Kappa Alpha",
    "Pi Kappa Phi",
    "Phi Kappa Tau",
    "Psi Upsilon",
    "Sigma Alpha Epsilon",
    "Sigma Chi",
    "Sigma Nu",
    "Sigma Phi Epsilon",
    "Tau Kappa Epsilon",
    "Theta Chi",
    "Theta Xi",
    "Zeta Beta Tau"
];
const MulticulturalOrganizations = [
    "Delta Epsilon Psi Fraternity, Inc.",
    "Delta Phi Lambda Sorority, Inc.",
    "Sigma Beta Rho Fraternity, Inc.",
    "Sigma Sigma Rho Sorority, Inc.",
    "La Unidad Latina, Lambda Upsilon Lambda Fraternity, Inc. (Associate Status)",
    "Lambda Theta Alpha Latin Sorority, Inc. (Associate Status)",
    "Lambda Theta Phi Latin Fraternity, Inc. (Associate Status)"
];
const NPHCOrganizations = [
    "Alpha Phi Alpha",
    "Alpha Kappa Alpha",
    "Kappa Alpha Psi",
    "Omega Psi Phi",
    "Delta Sigma Theta",
    "Phi Beta Sigma",
    "Zeta Phi Beta",
    "Sigma Gamma Rho"
];
const SpiritualReligiousOrganizations = [
    "Alpha Omega Campus Ministry",
    "Atlanta Christian Collegiate Fellowship",
    "BAPS Campus Fellowship",
    "Baptist Collegiate Ministries",
    "Campus Outreach",
    "Catholic Student Organization",
    "Chabad Jewish Student Group",
    "Chi Alpha",
    "Chinese Christian Fellowship"
];
const ServiceOrganizations = [
    "Alpha Phi Omega",
    "Habitat for Humanity",
    "MOVE (Mobilizing Opportunities for Volunteer Experiences)",
    "Engineers Without Borders",
    "Global Medical Brigade",
    "American Red Cross Club",
    "Women in Engineering (WIE)",
    "Student Veterans Association",
    "Sustainable Food Initiative",
    "Society of Women Engineers (SWE)",
    "Georgia Tech Relay For Life",
    "Hunger and Homelessness Committee",
    "College Republicans",
    "College Democrats",
    "Tech for Change",
    "Black Student Alliance Service Committee",
    "Out on Tech (LGBTQ+ service projects)",
    "Hispanic Recruitment and Educational Development (HRED)",
    "Sustainable Development Committee",
    "GIVE (Global Intercultural Volunteer Experience)",
    "Georgia Tech Association of Black Students",
    "Tech for Good",
    "Nonprofit Consulting Club",
    "Big Brothers Big Sisters of Metro Atlanta",
    "GT Gardening Club",
    "Mental Health Awareness Committee",
    "Environmental Justice League",
    "Tech Troupe (Theater and community engagement)"
];
const SocialRecreationalClubs = [
    "Adventure Club",
    "Board Game Club",
    "Climbing Club",
    "Cooking Club",
    "Cycling Club",
    "Dance Club",
    "Film Society",
    "Gaming Club",
    "Outdoor Recreation Georgia Tech (ORGT)",
    "Rock Climbing Club",
    "Scuba Diving Club",
    "Ski and Snowboard Club",
    "Ultimate Frisbee Club",
    "Wilderness Society",
    "Yoga Club",
    "Photography Club",
    "Tech Theatre Company",
    "Anime Club",
    "Ballet Club",
    "Society of Physics Students",
    "Sailing Club",
    "Dungeons and Dragons Club",
    "Running Club",
    "Hiking Club",
    "Badminton Club",
    "Intramural Sports",
    "G.I.T. FIT Programs",
    "Crafting Club",
    "Martial Arts Club",
    "Esports Club"
];
const AcademicOrganizations = [
    "Eta Kappa Nu (HKN) - Electrical and Computer Engineering Honor Society",
    "Institute of Electrical and Electronics Engineers (IEEE) - Professional association for electrical and electronic engineers",
    "Women in Electrical and Computer Engineering (WECE)",
    "Alpha Kappa Psi - Professional Business Fraternity",
    "Beta Alpha Psi - Honor Society for Accounting, Finance, and Information Systems",
    "Consult Your Community - Pro Bono Consulting Services",
    "Diversity in Business (DiB)",
    "Financial Management Association (FMA)",
    "Georgia Tech Marketing Association (GTMA)",
    "Honorary Accounting Organization (HAO)",
    "Management Information Systems Club",
    "Net Impact - Sustainability and social impact",
    "Society of Women Engineers (SWE)",
    "Society of Hispanic Professional Engineers (SHPE)",
    "American Institute of Aeronautics and Astronautics (AIAA)",
    "American Society of Civil Engineers (ASCE)",
    "American Society of Mechanical Engineers (ASME)",
    "Association for Computing Machinery (ACM)",
    "Engineers Without Borders (EWB)",
    "RoboJackets - Robotics Organization",
    "Quantum Computing Club",
    "Supercomputing @ GT - High-Performance Computing",
    "Women in Computing - Empowering women in computing disciplines",
    "HackGT - Hackathon organization",
    "RoboGrads - Graduate robotics organization",
    "Scheller College of Business Student Organizations",
    "Computer Science Graduate Student Organization",
    "Georgia Tech Chemistry Club",
    "Environmental and Sustainability Programs",
    "Student Government Association - Academic affairs committee",
    "Institute of Industrial and Systems Engineers (IISE)"
];







