// Interests
const Sports = [
    "Soccer/Football",
    "Basketball",
    "Cricket",
    "Tennis",
    "Golf",
    "Baseball",
    "American Football",
    "Rugby",
    "Boxing",
    "Mixed Martial Arts (MMA)",
    "Formula 1 Racing",
    "Ice Hockey",
    "Table Tennis",
    "Badminton",
    "Cycling",
    "Volleyball",
    "Track and Field (Athletics)",
    "Swimming",
    "Gymnastics",
    "Snooker",
    "Wrestling (Amateur/Olympic)",
    "Surfing",
    "Skiing",
    "Skateboarding",
    "Field Hockey",
    "Horse Racing",
    "Bowling",
    "Sailing",
    "Figure Skating",
    "Squash"
  ];
  

const Fitness = [
    "Running",
    "Walking",
    "Swimming",
    "Cycling",
    "Weightlifting",
    "Yoga",
    "Pilates",
    "HIIT (High-Intensity Interval Training)",
    "Dancing",
    "Jump Rope",
    "Rowing",
    "Climbing",
    "Hiking",
    "Spinning",
    "Zumba",
    "Barre",
    "Bodyweight Training",
    "Stretching",
    "Powerlifting",
    "Kettlebell Training",
    "TRX Training",
    "Aerobics",
    "Tai Chi",
    "Plyometrics",
    "Core Workouts",
    "Functional Training",
    "Resistance Band Training",
    "Circuit Training",
    "Elliptical Training",
    "Stair Climbing"
  ];
  

const MusicGenres = [
    "Pop",
    "Rock",
    "Hip Hop",
    "Electronic Dance Music (EDM)",
    "Jazz",
    "Classical",
    "R&B",
    "Country",
    "Reggae",
    "Blues",
    "Soul",
    "Funk",
    "Heavy Metal",
    "Punk",
    "Alternative Rock",
    "Indie Rock",
    "Disco",
    "House",
    "Techno",
    "Dubstep",
    "Trap",
    "Folk",
    "Latin",
    "Salsa",
    "K-pop",
    "Gospel",
    "Opera",
    "Grunge",
    "Ambient",
    "World Music",
    "Bedroom Pop",
    "Shoegaze",
    "Bossa Nova"
  ];
  

const Hobbies = [
    "Baking",
    "Birdwatching",
    "Calligraphy",
    "Candle Making",
    "Collecting (Coins, Stamps, etc.)",
    "Cooking",
    "DIY Projects",
    "Drawing",
    "Embroidery",
    "Furniture Restoration",
    "Gardening",
    "Homebrewing",
    "Jewelry Making",
    "Journaling",
    "Knitting",
    "Leatherworking",
    "Metalworking",
    "Model Building",
    "Origami",
    "Painting",
    "Perfume Making",
    "Photography",
    "Pottery",
    "Puzzle Solving",
    "Robotics",
    "Scrapbooking",
    "Sewing",
    "Soap Making",
    "Woodworking",
    "Writing"
  ];
  

const Games = [
    "Battleship",
    "Cards",
    "Checkers",
    "Chess",
    "Clue",
    "Dungeons & Dragons",
    "Monopoly",
    "Poker",
    "Risk",
    "Uno",
    "Assassin's Creed",
    "Baldur's Gate",
    "Call of Duty",
    "Counter-Strike 2",
    "Cyberpunk 2077: Phantom Liberty",
    "Elden Ring",
    "Final Fantasy",
    "Forza Motorsport",
    "God of War",
    "Grand Theft Auto",
    "Halo",
    "Minecraft",
    "Portal",
    "Red Dead Redemption",
    "Resident Evil",
    "Stardew Valley",
    "Starfield",
    "Terraria",
    "The Last of Us Part I (PC)",
    "The Legend of Zelda",
    "The Witcher 3: Wild Hunt",
    "Valorant"
  ];
  

const Social = [
    "Birthday Party",
    "Wedding",
    "Anniversary Celebration",
    "Graduation Party",
    "Baby Shower",
    "Housewarming Party",
    "Holiday Party",
    "Family Reunion",
    "Picnic",
    "Barbecue",
    "Potluck Dinner",
    "Corporate Event",
    "Networking Event",
    "Charity Gala",
    "Concert",
    "Theater Performance",
    "Art Exhibit",
    "Festival",
    "Community Fair",
    "Sports Game",
    "Game Night",
    "Dance Party",
    "Open Mic Night",
    "Film Screening",
    "Book Club Meeting",
    "Fashion Show",
    "Cooking Class",
    "Wine Tasting",
    "Trivia Night",
    "Meetup Group"
  ];
  

const Personality = [
    "Introvert",
    "Extrovert",
    "Ambivert",
    "Type A",
    "Type B",
    "Perfectionist",
    "Leader",
    "Follower",
    "Optimist",
    "Pessimist",
    "Realist",
    "Dreamer",
    "Analytical",
    "Creative",
    "Adventurous",
    "Caring",
    "Empathetic",
    "Charismatic",
    "Assertive",
    "Easygoing",
    "Nurturer",
    "Indecisive",
    "Pragmatic",
    "Visionary",
    "Skeptic",
    "Spontaneous",
    "Motivator",
    "Loyalist",
    "Rebel",
    "Traditionalist",
    "Night-Owl",
    "Early Riser"
  ];
  

const Food = [
    "Italian",
    "Mexican",
    "Chinese",
    "Indian",
    "Japanese",
    "Mediterranean",
    "French",
    "Thai",
    "Spanish",
    "Korean",
    "Vietnamese",
    "American",
    "Middle Eastern",
    "Caribbean",
    "British",
    "German",
    "African",
    "Brazilian",
    "Filipino",
    "Cajun",
    "Southern",
    "Scottish",
    "Indigenous",
    "Fusion",
    "Vegan",
    "Vegetarian",
    "Gluten-Free",
    "Paleo",
    "Raw",
    "Comfort Food"
  ];
  
// top 100 most popular movies
const Movies = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "Pulp Fiction",
    "The Lord of the Rings: The Return of the King",
    "Schindler's List",
    "Forrest Gump",
    "Inception",
    "Fight Club",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Star Wars: Episode V - The Empire Strikes Back",
    "The Matrix",
    "Goodfellas",
    "One Flew Over the Cuckoo's Nest",
    "Seven Samurai",
    "Se7en",
    "City of God",
    "The Silence of the Lambs",
    "It's a Wonderful Life",
    "Saving Private Ryan",
    "The Usual Suspects",
    "Leon: The Professional",
    "The Lion King",
    "Interstellar",
    "The Green Mile",
    "Star Wars: Episode IV - A New Hope",
    "Parasite",
    "Spirited Away",
    "The Pianist",
    "Terminator 2: Judgment Day",
    "Back to the Future",
    "Psycho",
    "Gladiator",
    "The Prestige",
    "The Departed",
    "Whiplash",
    "The Intouchables",
    "The Lord of the Rings: The Two Towers",
    "Memento",
    "Avengers: Infinity War",
    "Grave of the Fireflies",
    "Apocalypse Now",
    "Alien",
    "Sunset Boulevard",
    "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    "The Great Dictator",
    "Cinema Paradiso",
    "The Lives of Others",
    "The Shining",
    "Paths of Glory",
    "Django Unchained",
    "WALL-E",
    "American Beauty",
    "The Dark Knight Rises",
    "Oldboy",
    "Princess Mononoke",
    "Aliens",
    "Once Upon a Time in the West",
    "Coco",
    "Braveheart",
    "Das Boot",
    "Avengers: Endgame",
    "3 Idiots",
    "Toy Story",
    "Amadeus",
    "Inglourious Basterds",
    "Good Will Hunting",
    "Star Wars: Episode VI - Return of the Jedi",
    "Reservoir Dogs",
    "Requiem for a Dream",
    "Vertigo",
    "Eternal Sunshine of the Spotless Mind",
    "The Hunt",
    "Citizen Kane",
    "Lawrence of Arabia",
    "A Clockwork Orange",
    "The Father",
    "Dangal",
    "The Kid",
    "North by Northwest",
    "Singin' in the Rain",
    "Snatch",
    "2001: A Space Odyssey",
    "The Wolf of Wall Street",
    "The Truman Show",
    "Taxi Driver",
    "Scarface",
    "Joker",
    "Full Metal Jacket",
    "Toy Story 3",
    "Raging Bull",
    "The Big Lebowski",
    "No Country for Old Men",
    "Monty Python and the Holy Grail",
    "The Good, the Bad and the Ugly",
    "The Thing",
    "Heat",
    "A Beautiful Mind",
    "Blade Runner",
    "Up",
    "The Seventh Seal",
    "Jurassic Park",
    "Pan's Labyrinth",
    "Indiana Jones and the Last Crusade"
]
// top 100 most popular movies
const Series = [
    "Breaking Bad",
    "Game of Thrones",
    "Chernobyl",
    "The Wire",
    "Stranger Things",
    "The Sopranos",
    "Sherlock",
    "Friends",
    "The Office (US)",
    "The Mandalorian",
    "The Crown",
    "Rick and Morty",
    "True Detective",
  "The Simpsons",
  "Narcos",
  "Black Mirror",
  "Westworld",
  "Fargo",
  "House of Cards",
  "The Witcher",
  "Mindhunter",
  "Peaky Blinders",
  "Better Call Saul",
  "The Boys",
  "Mad Men",
  "Succession",
  "The Queen's Gambit",
  "The Haunting of Hill House",
  "Dark",
  "The Marvelous Mrs. Maisel",
  "Vikings",
  "The West Wing",
  "Lost",
  "How I Met Your Mother",
  "The Big Bang Theory",
  "Arrested Development",
  "Supernatural",
  "Brooklyn Nine-Nine",
  "Parks and Recreation",
  "The X-Files",
  "Dexter",
  "Seinfeld",
  "Band of Brothers",
  "Avatar: The Last Airbender",
  "The Twilight Zone",
  "Doctor Who",
  "Sons of Anarchy",
  "Prison Break",
  "Homeland",
  "Naruto: Shippuden",
  "House",
  "Buffy the Vampire Slayer",
  "Scrubs",
  "Mr. Robot",
  "The Handmaid's Tale",
  "The Umbrella Academy",
  "The Expanse",
  "Orange Is the New Black",
  "Spartacus",
  "GLOW",
  "Fleabag",
  "The Walking Dead",
  "Hannibal",
  "Lucifer",
  "12 Monkeys",
  "Supernatural",
  "BoJack Horseman",
  "Teen Wolf",
  "True Blood",
  "Bates Motel",
  "Justified",
  "Firefly",
  "The Good Place",
  "Grey's Anatomy",
  "Shameless",
  "This Is Us",
  "Arrow",
  "Daredevil",
  "The Flash",
  "The Punisher",
  "Jessica Jones",
  "Agents of S.H.I.E.L.D.",
  "Legion",
  "Deadwood",
  "Rome",
  "The Leftovers",
  "Big Little Lies",
  "Billions",
  "Boardwalk Empire",
  "The Americans",
  "The 100",
  "Outlander",
  "The Originals",
  "Teen Titans",
  "Fringe",
  "The Mentalist",
  "Person of Interest",
  "Bones",
  "Chilling Adventures of Sabrina",
  "The Vampire Diaries",
  "Smallville",
  "The Pacific",
  "Star Trek: The Next Generation",
  "The Last Kingdom"
]


// Organizations
const Sororities = [
    "Alpha Delta Pi",
    "Alpha Gamma Delta",
    "Alpha Omega Epsilon",
    "Alpha Phi",
    "Alpha Xi Delta",
    "Kappa Alpha Theta",
    "Phi Mu",
    "Zeta Tau Alpha"
];
const Fraternities = [
    "Alpha Epsilon Pi",
    "Alpha Sigma Phi",
    "Alpha Tau Omega",
    "Beta Theta Pi",
    "Chi Phi",
    "Chi Psi",
    "Delta Chi",
    "Delta Sigma Phi",
    "Delta Tau Delta",
    "Delta Upsilon",
    "Kappa Alpha Order",
    "Kappa Sigma",
    "Lambda Chi Alpha",
    "Phi Delta Theta",
    "Phi Gamma Delta",
    "Phi Kappa Psi",
    "Phi Kappa Sigma",
    "Phi Kappa Theta",
    "Phi Sigma Kappa",
    "Pi Kappa Alpha",
    "Pi Kappa Phi",
    "Phi Kappa Tau",
    "Psi Upsilon",
    "Sigma Alpha Epsilon",
    "Sigma Chi",
    "Sigma Nu",
    "Sigma Phi Epsilon",
    "Tau Kappa Epsilon",
    "Theta Chi",
    "Theta Xi",
    "Zeta Beta Tau"
];
const MulticulturalOrganizations = [
    "Delta Epsilon Psi Fraternity, Inc.",
    "Delta Phi Lambda Sorority, Inc.",
    "Sigma Beta Rho Fraternity, Inc.",
    "Sigma Sigma Rho Sorority, Inc.",
    "La Unidad Latina, Lambda Upsilon Lambda Fraternity, Inc. (Associate Status)",
    "Lambda Theta Alpha Latin Sorority, Inc. (Associate Status)",
    "Lambda Theta Phi Latin Fraternity, Inc. (Associate Status)"
];
const NPHCOrganizations = [
    "Alpha Phi Alpha",
    "Alpha Kappa Alpha",
    "Kappa Alpha Psi",
    "Omega Psi Phi",
    "Delta Sigma Theta",
    "Phi Beta Sigma",
    "Zeta Phi Beta",
    "Sigma Gamma Rho"
];
const SpiritualReligiousOrganizations = [
    "Alpha Omega Campus Ministry",
    "Atlanta Christian Collegiate Fellowship",
    "BAPS Campus Fellowship",
    "Baptist Collegiate Ministries",
    "Campus Outreach",
    "Catholic Student Organization",
    "Chabad Jewish Student Group",
    "Chi Alpha",
    "Chinese Christian Fellowship"
];
const ServiceOrganizations = [
    "Alpha Phi Omega",
    "Habitat for Humanity",
    "MOVE (Mobilizing Opportunities for Volunteer Experiences)",
    "Engineers Without Borders",
    "Global Medical Brigade",
    "American Red Cross Club",
    "Women in Engineering (WIE)",
    "Student Veterans Association",
    "Sustainable Food Initiative",
    "Society of Women Engineers (SWE)",
    "Georgia Tech Relay For Life",
    "Hunger and Homelessness Committee",
    "College Republicans",
    "College Democrats",
    "Tech for Change",
    "Black Student Alliance Service Committee",
    "Out on Tech (LGBTQ+ service projects)",
    "Hispanic Recruitment and Educational Development (HRED)",
    "Sustainable Development Committee",
    "GIVE (Global Intercultural Volunteer Experience)",
    "Georgia Tech Association of Black Students",
    "Tech for Good",
    "Nonprofit Consulting Club",
    "Big Brothers Big Sisters of Metro Atlanta",
    "GT Gardening Club",
    "Mental Health Awareness Committee",
    "Environmental Justice League",
    "Tech Troupe (Theater and community engagement)"
];
const SocialRecreationalClubs = [
    "Adventure Club",
    "Board Game Club",
    "Climbing Club",
    "Cooking Club",
    "Cycling Club",
    "Dance Club",
    "Film Society",
    "Gaming Club",
    "Outdoor Recreation Georgia Tech (ORGT)",
    "Rock Climbing Club",
    "Scuba Diving Club",
    "Ski and Snowboard Club",
    "Ultimate Frisbee Club",
    "Wilderness Society",
    "Yoga Club",
    "Photography Club",
    "Tech Theatre Company",
    "Anime Club",
    "Ballet Club",
    "Society of Physics Students",
    "Sailing Club",
    "Dungeons and Dragons Club",
    "Running Club",
    "Hiking Club",
    "Badminton Club",
    "Intramural Sports",
    "G.I.T. FIT Programs",
    "Crafting Club",
    "Martial Arts Club",
    "Esports Club"
];
const AcademicOrganizations = [
    "Eta Kappa Nu (HKN) - Electrical and Computer Engineering Honor Society",
    "Institute of Electrical and Electronics Engineers (IEEE) - Professional association for electrical and electronic engineers",
    "Women in Electrical and Computer Engineering (WECE)",
    "Alpha Kappa Psi - Professional Business Fraternity",
    "Beta Alpha Psi - Honor Society for Accounting, Finance, and Information Systems",
    "Consult Your Community - Pro Bono Consulting Services",
    "Diversity in Business (DiB)",
    "Financial Management Association (FMA)",
    "Georgia Tech Marketing Association (GTMA)",
    "Honorary Accounting Organization (HAO)",
    "Management Information Systems Club",
    "Net Impact - Sustainability and social impact",
    "Society of Women Engineers (SWE)",
    "Society of Hispanic Professional Engineers (SHPE)",
    "American Institute of Aeronautics and Astronautics (AIAA)",
    "American Society of Civil Engineers (ASCE)",
    "American Society of Mechanical Engineers (ASME)",
    "Association for Computing Machinery (ACM)",
    "Engineers Without Borders (EWB)",
    "RoboJackets - Robotics Organization",
    "Quantum Computing Club",
    "Supercomputing @ GT - High-Performance Computing",
    "Women in Computing - Empowering women in computing disciplines",
    "HackGT - Hackathon organization",
    "RoboGrads - Graduate robotics organization",
    "Scheller College of Business Student Organizations",
    "Computer Science Graduate Student Organization",
    "Georgia Tech Chemistry Club",
    "Environmental and Sustainability Programs",
    "Student Government Association - Academic affairs committee",
    "Institute of Industrial and Systems Engineers (IISE)"
];







